updates

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,7 +11,7 @@ if ! cd $(dirname "$0") ; then
 	exit 1
 fi
 
-W_SCRIPTDIR=$(pwd)
+WCONF_SCRIPTDIR=$(pwd)
 
 apps_to_check=''
 extra_env_vars=''
@@ -50,6 +50,11 @@ exit_error() {
 	exit 1
 }
 
+cmdecho()
+{
+    echo "# $@"
+    "$@"
+}
 
 getvalue()
 {
@@ -75,37 +80,31 @@ PACKAGE_BUGREPORT="${PACKAGE_URL}"
 PACKAGE_VERSION="${VERSION}"
 
 #==========================================================
-# ./configure release [xz|gz|lz|zst]
+# ./configure release [xz|gz|lz|bz2|zst]
 
-if [ "$1" = "release" ] ; then
-	srcdir=${W_SCRIPTDIR}
+if [ "$1" = "release" ] || [ "$1" = "dist" ] ; then
+	srcdir=${WCONF_SCRIPTDIR}
 	outdir=${PACKAGE}-${VERSION}
-	cd ..
-	rm -rf ${outdir}
-	if [ "$2" = "dist" ] ; then
-		# force creation of tarfile, copy the whole dir
-		shift
-		shift
-		cp -rf ${srcdir} ${outdir}
-		cd ${outdir}
-		git clean -dfx
-		rm -rf .*
-		cd ..
-	else
-		if command -v git >/dev/null; then
-			printf "Run 'git clean -dfx'? [y/N]: "
-			read anzwer
-			case $anzwer in y|Y)
-				cd ${srcdir}
-				echo '# git clean -dfx'
-				git clean -dfx
-				cd ..
-				;;
-			esac
-		fi
-		mkdir -p ${outdir}
-		cp -rf ${srcdir}/* ${outdir}/
+	if [ ! -d .git ] ; then
+		echo "Warning: no .git directory, will not be able to perform 'git clean'"
 	fi
+	if [ ! -d .git ] ; then
+		echo "Warning: no .gitignore file, it contains rules to delete unwanted files, the release tarball may not be suitable for release"
+	fi
+	if [ "$outdir" = "$(basename $srcdir)" ] ; then
+		echo "ERROR: output dir ($outdir) is the also input directory"
+		exit 1
+	fi
+	cmdecho cd ..
+	cmdecho rm -rf ${outdir}
+	cmdecho cp -rf ${srcdir} ${outdir}
+	cmdecho mkdir -p ${outdir}
+	cmdecho cd ${outdir}
+	if command -v git >/dev/null; then
+		cmdecho git clean -dfx
+	fi
+	rm -rf .[a-z]* .[A-Z]* .[0-9]*
+	cmdecho cd ..
 	#--
 	echo "# tar -vcf ${outdir}.tar ${outdir}"
 	tar -vcf ${outdir}.tar ${outdir}
@@ -116,16 +115,17 @@ if [ "$1" = "release" ] ; then
 	case $comp in
 		gz)  cmd=gzip    ;;
 		lz)  cmd=lzip    ;;
+		bz2) cmd=bzip2   ;;
 		zst) cmd=zstd    ;;
 		*)   cmd=${comp} ;;
 	esac
 	rm -f ${outdir}.tar.${comp}
-	echo "# ${cmd} ${outdir}.tar"
-	if ${cmd} ${outdir}.tar ; then
+	if cmdecho ${cmd} ${outdir}.tar ; then
 		echo "*** ${outdir}.tar.${comp} has been created..."
+		exit 0
 	fi
 	rm -f ${outdir}.tar
-	exit
+	exit 1
 fi
 
 # w_conf/gettext: ./configure po|pot
@@ -474,8 +474,8 @@ w_require_gnu_make()
 
 #==========================================================
 
-#test "$CC"    || CC='gcc'
-#test "$CXX"   || CXX='g++'
+#test "$CC"    || CC='cc'
+#test "$CXX"   || CXX='c++'
 test "$STRIP"  || STRIP='strip'
 test "$AR"     || AR='ar'
 test "$AS"     || AS='as'
@@ -505,8 +505,8 @@ infodir='${datarootdir}/info'
 mandir='${datarootdir}/man'
 localedir='${datarootdir}/locale'
 runstatedir='${localstatedir}/run'
-top_builddir="${W_SCRIPTDIR}"
-top_srcdir="${W_SCRIPTDIR}"
+top_builddir="${WCONF_SCRIPTDIR}"
+top_srcdir="${WCONF_SCRIPTDIR}"
 builddir=.
 srcdir=.
 
@@ -807,13 +807,14 @@ esac
 TARGET_OS="$OS_TARGET"
 
 #==========================================================
+# PROJECT_FLAGS go first (can be overridden)
 
-CFLAGS="$CFLAGS $PROJECT_CFLAGS"
-CPPFLAGS="$CPPFLAGS $PROJECT_CPPFLAGS"
-CXXFLAGS="$CXXFLAGS $PROJECT_CXXFLAGS"
-LDFLAGS="$LDFLAGS $PROJECT_LDFLAGS"
-LXXFLAGS="$LXXFLAGS $PROJECT_LXXFLAGS"
-LIBS="$LIBS $PROJECT_LIBS"
+CFLAGS="$PROJECT_CFLAGS $CFLAGS"
+CPPFLAGS="$PROJECT_CPPFLAGS $CPPFLAGS"
+CXXFLAGS="$PROJECT_CXXFLAGS $CXXFLAGS"
+LDFLAGS="$PROJECT_LDFLAGS $LDFLAGS"
+LXXFLAGS="$PROJECT_LXXFLAGS $LXXFLAGS"
+LIBS="$PROJECT_LIBS $LIBS"
 
 #==========================================================
 
